language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:afd2e57ef4c099a0b767232d23747b251069f3d2
  - docker run -d -p 8080:8080 kodebox/codechain:afd2e57ef4c099a0b767232d23747b251069f3d2 --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
script:
  - yarn test --verbose
  - yarn build
  - yarn test-int --verbose
notifications:
  webhooks: https://webhooks.gitter.im/e/8908c378a5e2669893ab
services:
  - docker
cache: yarn
