language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:9e5c4831feb7ed5ae4dbf469ef31f5d0f207806f
  - docker run -d -p 8080:8080 kodebox/codechain:9e5c4831feb7ed5ae4dbf469ef31f5d0f207806f --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
script:
  - yarn test --verbose
  - yarn build
  - yarn test-int --verbose
notifications:
  webhooks: https://webhooks.gitter.im/e/8908c378a5e2669893ab
services:
  - docker
cache: yarn
