language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:b4e05e83b7c8ca21df677ccff26a2d11914b71e3 
  - docker run -d -p 8080:8080 kodebox/codechain:b4e05e83b7c8ca21df677ccff26a2d11914b71e3  --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
script:
  - yarn test --verbose
  - yarn build
  - yarn test-int --verbose
notifications:
  webhooks: https://webhooks.gitter.im/e/8908c378a5e2669893ab
services:
  - docker
cache: yarn
