language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:fe9b3c171f6635f4dcb4eece29f4e2a770665bd9 
  - docker run -d -p 8080:8080 kodebox/codechain:fe9b3c171f6635f4dcb4eece29f4e2a770665bd9  --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
script:
  - yarn test --verbose
  - yarn build
  - yarn test-int --verbose
notifications:
  webhooks: https://webhooks.gitter.im/e/8908c378a5e2669893ab
services:
  - docker
cache: yarn
