language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:45ce9a1e1df616e73b88dfe0d264e508f804bf9c
  - docker run -d -p 8080:8080 kodebox/codechain:45ce9a1e1df616e73b88dfe0d264e508f804bf9c --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
script:
  - yarn test --verbose
  - yarn build
  - yarn test-int --verbose
notifications:
  webhooks: https://webhooks.gitter.im/e/8908c378a5e2669893ab
services:
  - docker
cache: yarn
